export { AdminController } from './api/admin.controller';
// export { AppController } from './api/app.controller';
export { AuthController } from './api/auth.controller';
export { CategoryController } from './api/category.controller';
export { ContactController } from './api/contact.controller';
export { FcmTokenController } from './api/fcm_token.controller';
export { ForgotPasswordController } from './api/forgot-password.controller';
export { NotificationController } from './api/notification.controller';
export { PushNotificationController } from './api/push_notification.controller';
export { RatetingController } from './api/rateting.controller';
export { RegisterController } from './api/register.controller';
export { ServiceController } from './api/service.controller';
export { TaskController } from './api/task.controller';
export { TaskerController } from './api/tasker.controller';
export { UserController } from './api/user.controller';
